stages:
  - upload
  - build
  - test
  - deploy_synapse_package
  - deploy_synapse_notebook
  - deploy_trigger


upload:
  image: mcr.microsoft.com/azure-cli:2.43.0
  stage: upload
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az storage fs directory upload -f metadata --account-name ${AZ_STORAGE_ACCOUNT} -s "mappingfiles" -d "" --recursive


build:
  image: python:3.8
  stage: build
  script:
    - pip install poetry twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl

test:
  image: python:3.8
  stage: test
  script:
    - echo "Not implemented"


deploy_synapse_package:
  image: mcr.microsoft.com/azure-cli:2.41.0
  stage: deploy_synapse_package
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az synapse workspace-package upload --workspace-name $SYNAPSE_WORKSPACE_NAME --package dist/*.whl
  when: manual

deploy_synapse_notebook:
  image: mcr.microsoft.com/azure-cli:2.41.0
  stage: deploy_synapse_notebook
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az synapse notebook create --workspace-name $SYNAPSE_WORKSPACE_NAME --name RunCloudBillingTool --file @"notebooks/RunCloudBillingTool.ipynb" --spark-pool-name cbtparkpool
  when: manual

deploy_trigger:
  image: mcr.microsoft.com/azure-cli:2.41.0
  stage: deploy_trigger
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az synapse trigger delete --workspace-name $SYNAPSE_WORKSPACE_NAME --name RunCloudBillingToolTrigger --yes
    - az synapse notebook trigger create --name RunCloudBillingToolTrigger --notebook-name RunCloudBillingTool --workspace-name $SYNAPSE_WORKSPACE_NAME --recurrence "59 23 28-31 * *"
  when: manual