stages:
  - deploy_dashboard

deploy_dashboard:
  stage: deploy_dashboard
  image: grafana/grafana-oss
  script:
    - grafana-cli login --api-key=$GRAFANA_API_KEY
    - grafana-cli dashboards import --file=grafana/CloudBillingDashboard.json --folder=BillingDeploy --overwrite
  when: manual

