stages:
  - upload
  - build
  - test
  - deploy_synapse


upload:
  image: mcr.microsoft.com/azure-cli:2.43.0
  stage: upload
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az config set extension.use_dynamic_install=yes_without_prompt
    - az storage blob directory upload -c mappingfiles --account-name ${AZ_STORAGE_ACCOUNT} -s "data/mappingfiles/" -d ""


build:
  image: python:3.8
  stage: build
  script:
    - pip install poetry twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl

test:
  image: python:3.8
  stage: test
  script:
    - echo "Not implemented"


deploy_synapse:
  image: mcr.microsoft.com/azure-cli:2.41.0
  stage: deploy_synapse
  script:
    - az login --service-principal -u ${AZ_APP_ID} -p ${AZ_SECRET} --tenant ${AZ_TENANT}
    - az synapse workspace-package upload --workspace-name $SYNAPSE_WORKSPACE_NAME --package dist/*.whl
  when: manual
