apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        resources:
          requests:
            cpu: {{ .Values.image.cpu }}
            memory: {{ .Values.image.memory }}
        image: "{{ .Values.image.image }}:{{ .Values.image.version | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - secretRef:
            name: azure-credentials
        command:
        - "python"
        args:
        - "cloudbillingtool-run.py"
        - "--jdbc_url"
        - "$(JDBC_URL)"
        - "--azure_sa_name"
        - "$(AZURE_SA_NAME)"
        - "--azure_sa_key"
        - "$(AZURE_SA_KEY)"
        - "--download"
      imagePullSecrets:
      - name: gitlab-deploy-token