apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.image }}:{{ .Values.image.version | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "cloudbillingtool-run.py", "--hetzner_data", "/config/hetzner/*.csv", "--azure_data", "/config/azure/*.csv", "--aws_data", "", "--metadata", "/config/metadata", "--output_path", "/config/output/" ]
#          volumeMounts:
#            - name: config-volume
#              mountPath: /config
#      volumes:
#        - name: config-volume
#          configMap:
#            name: cloudbillingtool-configmap