apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbillingtool
  labels:
    app: cloudbillingtool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudbillingtool
  template:
    metadata:
      labels:
        app: cloudbillingtool
    spec:
      containers:
        - name: cloudbillingtool
          image: python:3.8-slim-buster
          command: ["python", "cloudbillingtool-run.py", "--hetzner_data", "/config/hetzner/*.csv", "--azure_data", "/config/azure/*.csv", "--aws_data", "", "--metadata", "/config/metadata", "--output_path", "/config/output/" ]
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: cloudbillingtool-configmap