{
 "title": "SenecBillingDashBoard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CostResourceTagsList",
    "query": "SELECT CostResourceTag FROM allbilling_tags;"
   },
   {
    "name": "Provider",
    "query": "Select distinct Provider from allbilling;"
   }
  ]
 },
 "panels": [
  {
   "title": "Cost by Provider and Tag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "database": "senecallbillsv2",
     "dataset": "cloudbillingtool",
     "expression": {
      "from": { "property": { "name": "allbillsv3", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        { "property": { "name": "Date", "type": "dateTime" }, "type": "groupBy" }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Costs", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "$Provider", "name": "==", "value": "'$Provider'" },
           "property": { "name": "Provider", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        },
        {
         "expressions": [
          {
           "operator": { "name": "has", "value": "" },
           "property": {
            "name": "CostResourceTag[\"`indexer`\"]",
            "type": "string"
           },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "allbillsv3\n| where $__timeFilter(Date)\n| where Provider == '$Provider'\n| where CostResourceTag has ('${CostResourceTagsList:raw}')\n| summarize sum(Costs) by Date",
     "querySource": "raw",
     "rawSql": "SELECT SUM(Costs), Date\nFROM cloudbillingtool.dbo.allbilling \nWHERE Provider='$Provider' AND $__timeFilter(Date) AND\nCostResourceTag like '%${CostResourceTagsList:raw}%'\nGROUP BY Date "
    },
    {}
   ]
  },
  {
   "title": "Total Costs by Provider",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "senecallbillsv2",
     "dataset": "cloudbillingtool",
     "expression": {
      "from": { "property": { "name": "allbillsv3", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "allbillsv3\n| where $__timeFilter(Date)\n| summarize sum(Costs) by Provider",
     "querySource": "raw",
     "rawSql": "SELECT TOP(50) SUM(Costs), Provider \nFROM cloudbillingtool.dbo.allbilling \nWHERE $__timeFilter(Date)\nGROUP BY Provider "
    }
   ]
  },
  {
   "title": "Summary of Cost by CostResourceTag",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "database": "senecallbillsv2",
     "expression": {
      "from": { "property": { "name": "allbillsv3", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [
        {
         "property": {
          "name": "CostResourceTag[\"`indexer`\"]",
          "type": "string"
         },
         "type": "groupBy"
        }
       ],
       "type": "and"
      },
      "reduce": {
       "expressions": [
        { "property": { "name": "Costs", "type": "number" }, "reduce": { "name": "sum", "type": "function" }, "type": "reduce" }
       ],
       "type": "and"
      },
      "where": {
       "expressions": [
        {
         "expressions": [
          {
           "operator": { "labelValue": "$Provider", "name": "==", "value": "'$Provider'" },
           "property": { "name": "Provider", "type": "string" },
           "type": "operator"
          }
         ],
         "type": "or"
        }
       ],
       "type": "and"
      }
     },
     "query": "allbillsv3\n| where $__timeFilter(Date)\n| where Provider == '$Provider'\n| mv-expand array_1 = CostResourceTag\n| summarize sum(Costs) by tostring(array_1)",
     "querySource": "visual",
     "rawSql": " SELECT SUM(costs), CostResourceTag FROM allbilling  CROSS APPLY STRING_SPLIT(CostResourceTag, ',') Group by CostResourceTag"
    }
   ]
  }
 ]
}