{
 "title": "SenecBillingDashBoard",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CostResourceTagsList",
    "query": "SELECT CostResourceTag FROM allbilling_tags;"
   }
  ]
 },
 "panels": [
  {
   "title": "Cost by Provider and Tag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT SUM(Costs) as Azure, Date\nFROM dbo.allbilling \nWHERE Provider='azure' AND $__timeFilter(Date) AND\nCostResourceTag like '%${CostResourceTagsList:raw}%'\nGROUP BY Date "
    },
    {
     "rawSql": "SELECT SUM(Costs) as Hetzner, Date\nFROM dbo.allbilling \nWHERE Provider='hetzner' AND $__timeFilter(Date) AND\nCostResourceTag like '%${CostResourceTagsList:raw}%'\nGROUP BY Date "
    }
   ]
  },
  {
   "title": "Total Costs by Provider",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(Costs), Provider \nFROM dbo.allbilling \nWHERE $__timeFilter(Date)\nGROUP BY Provider "
    }
   ]
  },
  {
   "title": "Summary of Cost by CostResourceTag",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "\nSelect [CostResourceTag], [azure],  [hetzner] \nFROM (\n\nSELECT SUM(costs) costs, Value as CostResourceTag, Provider \nFROM allbilling  CROSS APPLY STRING_SPLIT(CostResourceTag, ',')\nWHERE  $__timeFilter(Date) \nGroup by Value, Provider\n\n) As SourceTable\nPIVOT\n(\nSUM(Costs)\nFOR [Provider] IN ([azure], [hetzner])\n) as Pvt"
    }
   ]
  },
  {
   "title": "Costs Items",
   "type": "table",
   "gridPos": { "h": 18, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "Select Top(10000) * FROM allbilling\nWHERE\n$__timeFilter(Date) AND\nCostResourceTag like '%${CostResourceTagsList:raw}%'"
    }
   ]
  }
 ]
}